SELECT * FROM funcionario;
SELECT * FROM produto;
SELECT * FROM requisicao;
SELECT * FROM cotacao;
SELECT * FROM ordemCompra;
SELECT * FROM cliente;
SELECT * FROM pedido;
SELECT * FROM fornecedor;
SELECT * FROM ProdutoReq;
